-- ============================================================================
-- CLEANUP DE TABELAS DE MODULOS REMOVIDOS  —  REFERENCIA, NAO EXECUTAVEL
-- ============================================================================
-- ATENCAO: este arquivo NAO deve mais ser rodado em bloco. A versao antiga
-- (um BEGIN/COMMIT com ~91 DROP TABLE CASCADE) ENVELHECEU e passou a listar
-- tabelas que voltaram a ser usadas — roda-la dropava dado de producao vivo.
--
-- O cleanup seguro virou migration versionada:
--   supabase/migrations/20260731130000_drop_orphan_modules.sql
-- que dropa apenas as tabelas confirmadas orfas E vazias (auditadas em
-- 2026-07-31). Prefira migrations a rodar SQL solto no Editor.
--
-- Abaixo fica so o mapa do que e o que, para nao repetir o erro.
-- ============================================================================

-- ── JA DROPADAS (migration 20260731130000) — orfas, sem ref no codigo, vazias ──
--   cs_interactions, nps_survey_schedule,
--   cs_events, cs_event_participant_sessions, cs_event_participant_profiles,
--   cs_event_feed_posts, cs_event_feed_likes, cs_event_schedule_items,
--   cs_event_schedule_bookmarks, cs_event_materials, cs_event_connections,
--   financial_accounts, financial_categories, financial_entries,
--   asaas_customers, asaas_webhooks,
--   wa_communities, wa_community_groups, wa_community_campaigns,
--   wa_community_campaign_items

-- ── NUNCA DROPAR — VIVAS (existem no banco E referenciadas por codigo) ─────────
--   transactions              -> criada jul/2026, usada no comercial
--   email_automation_runs     -> insert em process-automation-rules / email-automation-tick
--   email_templates           -> templates de e-mail
--   cs_objectives             -> referenciada por codigo vivo
--   cs_success_metrics        -> referenciada por codigo vivo
--   cs_touchpoints            -> referenciada por codigo vivo
--   cs_engagement_metrics     -> referenciada por codigo vivo
--   cs_event_rsvps            -> referenciada por codigo vivo
--   instagram_messages        -> referenciada pelo ai-sales-agent
--   instagram_conversations   -> referenciada pelo ai-sales-agent
--   (Antes de dropar qualquer uma: confirmar 0 ref em src/ + supabase/functions
--    E 0 linhas via `supabase inspect db table-stats`.)

-- ── JA AUSENTES DO BANCO (nao existem mais; dropar seria no-op) ────────────────
--   Customer Success: cs_health_scores, cs_health_overrides, cs_alerts,
--     cs_ai_actions, cs_ai_daily_briefings, cs_journey_stages, cs_onboardings,
--     cs_onboarding_steps, cs_advisor_meetings, cs_advisor_clients, cs_advisors,
--     cs_support_tickets, cs_support_metrics, cs_testimonials, cs_churn_overrides,
--     clients, client_timeline_events, client_insights, client_checkins,
--     member_engagement, member_status, nps_responses, tickets, support_tickets
--   Eventos: event_costs, event_invitations, marketing_events, webinar_configs,
--     webinar_registrations
--   RH: hr_vacancies, hr_candidates, hr_applications, hr_interviews,
--     hr_assessments, hr_offers, hr_pipeline_stages, hr_scoring_rubrics,
--     hr_timeline_events
--   Financeiro/NFSe: financial_ledger, dre_lines, accounts_receivable, nfse,
--     nfse_config, nfse_webhooks, nfse_history, fiscal_config
--   Instagram: instagram_profiles, instagram_accounts, instagram_posts,
--     instagram_stories, instagram_webhooks
--   Knowledge Base: kb_pages, kb_presence, kb_autosaves, kb_page_versions
--   Organograma/Growth/CEO: org_chart_nodes, growth_metrics, ceo_briefings,
--     business_context, objectives, testimonials
-- ============================================================================
